# Generated by Django 5.0.3 on 2024-03-30 17:49

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", apps.users.managers.CustomManager()),
            ],
        ),
    ]
